#!/bin/bash

echo "📋 VERCEL ENVIRONMENT VARIABLES - COPY & PASTE GUIDE"
echo "====================================================="
echo ""
echo "Go to: https://vercel.com/al-wilsons-projects/ai-chatbot/settings/environment-variables"
echo ""
echo "---------------------------------------------------"
echo "1. UPDATE POSTGRES_URL"
echo "---------------------------------------------------"
echo "Variable name: POSTGRES_URL"
echo "Environment: Production (uncheck others)"
echo ""
echo "Value to paste:"
echo "postgresql://postgres:GZGLrGQV4bGRdrTZ@db.iomzbddkmykfruslybxq.supabase.co:5432/postgres"
echo ""
echo "---------------------------------------------------"
echo "2. UPDATE NEXT_PUBLIC_SUPABASE_URL"
echo "---------------------------------------------------"
echo "Variable name: NEXT_PUBLIC_SUPABASE_URL"
echo "Environment: All Environments"
echo ""
echo "Value to paste:"
echo "https://iomzbddkmykfruslybxq.supabase.co"
echo ""
echo "---------------------------------------------------"
echo "3. UPDATE NEXTAUTH_URL"
echo "---------------------------------------------------"
echo "Variable name: NEXTAUTH_URL"
echo "Environment: Production"
echo ""
echo "Value to paste:"
echo "https://ai-chatbot-five-gamma-48.vercel.app"
echo ""
echo "---------------------------------------------------"
echo "4. ADD DATABASE_URL (if not already set correctly)"
echo "---------------------------------------------------"
echo "Variable name: DATABASE_URL"
echo "Environment: Production"
echo ""
echo "Value to paste:"
echo "postgresql://postgres:GZGLrGQV4bGRdrTZ@db.iomzbddkmykfruslybxq.supabase.co:5432/postgres"
echo ""
echo "---------------------------------------------------"
echo "5. ADD DIRECT_URL (if not already set correctly)"
echo "---------------------------------------------------"
echo "Variable name: DIRECT_URL"
echo "Environment: Production"
echo ""
echo "Value to paste:"
echo "postgresql://postgres:GZGLrGQV4bGRdrTZ@db.iomzbddkmykfruslybxq.supabase.co:5432/postgres"
echo ""
echo "====================================================="
echo "✅ AFTER SAVING:"
echo "====================================================="
echo ""
echo "Vercel will automatically redeploy (takes ~2 minutes)"
echo "Then test:"
echo "  https://ai-chatbot-five-gamma-48.vercel.app"
echo ""
echo "The app should load instead of showing a blank page!"
echo ""
