export interface InsightChunk {
  id: string;
  title: string;
  meaning: string;
  quote: string;
  sourceType: 'perplexity' | 'upload' | 'url' | 'manual';
  sourceName: string;
  sourceUrl?: string;
  sourceDomain?: string;
  status: 'pending' | 'live' | 'dismissed';
  flaggedCount: number;
  relationships: Array<{
    type: 'flagged_from' | 'approved_by' | 'dismissed_by';
    actor?: string;
    at: string;
    reason?: string;
    source?: { domain?: string; url?: string };
  }>;
  firstSeenAt: string;
  lastSeenAt?: string;
  isDuplicate?: boolean;
  tags?: string[];
}

export interface UploadedContent {
  id: string;
  name: string;
  type: 'pdf' | 'video' | 'text' | 'url';
  uploadedAt: string;
  uploadedBy: string;
  chunksGenerated: number;
  chunkIds: string[];
}

export interface GuardrailTopic {
  id: string;
  value: string;
  note?: string;
  createdAt: string;
  createdBy: string;
}

export interface GuardrailPhrase {
  id: string;
  value: string;
  rewriteHint?: string;
  createdAt: string;
  createdBy: string;
}

export const MOCK_INSIGHT_CHUNKS: InsightChunk[] = [
  // PENDING CHUNKS (12 total, 2 marked as duplicates)
  {
    id: 'chunk-p-001',
    title: 'Glen served on the board of the Federal Reserve Bank of Chicago',
    meaning: 'Glen Tullman was appointed to serve on the board of directors of the Federal Reserve Bank of Chicago, representing the healthcare and technology sectors. This role gave him insights into economic policy and financial systems.',
    quote: 'During his tenure on the Federal Reserve Board, Tullman provided valuable perspectives on how healthcare innovation and digital transformation were reshaping the American economy.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 24',
    sourceDomain: 'chicagofed.org',
    sourceUrl: 'https://chicagofed.org/board-members',
    status: 'pending',
    flaggedCount: 0,
    relationships: [],
    firstSeenAt: 'Oct 24, 2024, 9:15 AM',
    tags: ['Career', 'Leadership'],
  },
  {
    id: 'chunk-p-002',
    title: 'Founded Livongo Health in 2014',
    meaning: 'Glen Tullman co-founded Livongo Health in 2014 with the mission to empower people with chronic conditions to live better lives. The company pioneered applied health signals and personalized health nudges.',
    quote: 'We started Livongo because we believed technology could fundamentally change how people manage chronic conditions like diabetes. It wasn\'t just about tracking data—it was about turning that data into actionable insights that improve lives.',
    sourceType: 'upload',
    sourceName: 'glen-bio.pdf',
    status: 'pending',
    flaggedCount: 2,
    relationships: [
      {
        type: 'flagged_from',
        actor: 'Aaron Thomas',
        at: 'Oct 20, 2024, 2:30 PM',
        reason: 'Verify founding year - some sources say 2013',
      },
      {
        type: 'flagged_from',
        actor: 'Ashley',
        at: 'Oct 21, 2024, 10:15 AM',
        reason: 'Need more detail on co-founders',
      },
    ],
    firstSeenAt: 'Oct 18, 2024, 11:00 AM',
    lastSeenAt: 'Oct 21, 2024, 10:15 AM',
    tags: ['Career', 'Company', 'Livongo'],
  },
  {
    id: 'chunk-p-003',
    title: 'Livongo IPO raised $355 million in 2019',
    meaning: 'Livongo Health went public in July 2019, raising $355 million in one of the most successful healthcare technology IPOs of the year. The stock price doubled on the first day of trading.',
    quote: 'The market validation we received on IPO day was incredible, but more importantly, it proved that investors believed in our mission to make chronic condition management accessible and effective for millions of people.',
    sourceType: 'url',
    sourceName: 'Forbes Article',
    sourceDomain: 'forbes.com',
    sourceUrl: 'https://forbes.com/livongo-ipo-2019',
    status: 'pending',
    flaggedCount: 0,
    relationships: [],
    firstSeenAt: 'Oct 23, 2024, 4:45 PM',
    isDuplicate: true,
    tags: ['Company', 'Livongo'],
  },
  {
    id: 'chunk-p-004',
    title: 'Teladoc acquired Livongo for $18.5 billion in 2020',
    meaning: 'In August 2020, Teladoc Health acquired Livongo in a landmark $18.5 billion merger, creating a combined virtual care and chronic condition management platform. This was one of the largest digital health acquisitions in history.',
    quote: 'The combination of Teladoc and Livongo created something truly unique—a whole-person virtual care platform that could serve members across the full spectrum of their health needs, from acute care to chronic condition management.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 24',
    sourceDomain: 'wsj.com',
    sourceUrl: 'https://wsj.com/teladoc-livongo-merger',
    status: 'pending',
    flaggedCount: 3,
    relationships: [
      {
        type: 'flagged_from',
        actor: 'Aaron Thomas',
        at: 'Oct 24, 2024, 9:20 AM',
        reason: 'Clarify Glen\'s role post-acquisition',
      },
      {
        type: 'flagged_from',
        actor: 'Ashley',
        at: 'Oct 24, 2024, 11:30 AM',
        reason: 'Add context about deal structure',
      },
      {
        type: 'flagged_from',
        actor: 'Glen',
        at: 'Oct 24, 2024, 2:00 PM',
        reason: 'I want to emphasize the strategic rationale more',
      },
    ],
    firstSeenAt: 'Oct 24, 2024, 9:00 AM',
    lastSeenAt: 'Oct 24, 2024, 2:00 PM',
    tags: ['Company', 'Livongo', 'Healthcare'],
  },
  {
    id: 'chunk-p-005',
    title: 'CEO of Transcarent since 2020',
    meaning: 'Glen Tullman founded and became CEO of Transcarent in 2020, a health and care experience company focused on making healthcare more accessible, inclusive, and delivering the best results at the best price.',
    quote: 'At Transcarent, we\'re tackling the fundamental problem that healthcare is too complex, too expensive, and too hard to navigate. We believe every person deserves access to high-quality care without the confusion and frustration that exists today.',
    sourceType: 'upload',
    sourceName: 'transcarent-press-kit.pdf',
    status: 'pending',
    flaggedCount: 0,
    relationships: [],
    firstSeenAt: 'Oct 19, 2024, 8:30 AM',
    tags: ['Career', 'CEO', 'Company', 'Transcarent'],
  },
  {
    id: 'chunk-p-006',
    title: 'Transcarent raised over $450 million in funding',
    meaning: 'Transcarent has raised more than $450 million from leading investors including General Catalyst, 7wireVentures, and the venture arms of major health systems. The funding reflects strong investor confidence in the company\'s mission.',
    quote: 'The capital we\'ve raised allows us to build the infrastructure and technology needed to transform healthcare delivery. But more importantly, our investors share our vision that healthcare should work for everyone.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 24',
    sourceDomain: 'techcrunch.com',
    sourceUrl: 'https://techcrunch.com/transcarent-funding',
    status: 'pending',
    flaggedCount: 1,
    relationships: [
      {
        type: 'flagged_from',
        actor: 'Aaron Thomas',
        at: 'Oct 23, 2024, 3:45 PM',
        reason: 'Update with latest funding round',
      },
    ],
    firstSeenAt: 'Oct 22, 2024, 1:15 PM',
    lastSeenAt: 'Oct 23, 2024, 3:45 PM',
    tags: ['Company', 'Transcarent', 'Healthcare'],
  },
  {
    id: 'chunk-p-007',
    title: 'Previously CEO of Allscripts for 13 years',
    meaning: 'Before founding Livongo, Glen served as CEO of Allscripts Healthcare Solutions for 13 years, growing it into one of the largest healthcare IT companies. Under his leadership, the company completed several strategic acquisitions.',
    quote: 'My time at Allscripts taught me that technology alone isn\'t enough—you need to understand the workflows, the people, and the real problems healthcare providers face every day. That experience shaped everything I\'ve done since.',
    sourceType: 'url',
    sourceName: 'LinkedIn Profile',
    sourceDomain: 'linkedin.com',
    sourceUrl: 'https://linkedin.com/in/glentullman',
    status: 'pending',
    flaggedCount: 0,
    relationships: [],
    firstSeenAt: 'Oct 21, 2024, 5:20 PM',
    tags: ['Career', 'CEO', 'Company', 'Allscripts'],
  },
  {
    id: 'chunk-p-008',
    title: 'Author of "On My Own Two Feet"',
    meaning: 'Glen co-authored "On My Own Two Feet," a book about financial literacy and independence aimed at helping young people understand money management and build financial confidence.',
    quote: 'Financial health is foundational to overall wellbeing. If you\'re stressed about money, it affects everything—your physical health, your relationships, your ability to focus on what matters. That\'s why financial literacy is so important.',
    sourceType: 'manual',
    sourceName: 'Manual Entry',
    status: 'pending',
    flaggedCount: 0,
    relationships: [],
    firstSeenAt: 'Oct 20, 2024, 10:00 AM',
    isDuplicate: true,
    tags: ['Philosophy', 'Healthcare'],
  },
  {
    id: 'chunk-p-009',
    title: 'Strong advocate for value-based care models',
    meaning: 'Throughout his career, Glen has been a vocal proponent of shifting healthcare from fee-for-service to value-based care models that reward outcomes rather than volume. He believes this alignment of incentives is key to fixing healthcare.',
    quote: 'The fundamental problem with healthcare today is that we pay for activity, not results. Until we align incentives around outcomes and value, we\'ll continue to have a system that\'s too expensive and doesn\'t deliver the results people deserve.',
    sourceType: 'upload',
    sourceName: 'healthcare-conference-2023.txt',
    status: 'pending',
    flaggedCount: 0,
    relationships: [],
    firstSeenAt: 'Oct 19, 2024, 2:40 PM',
    tags: ['Philosophy', 'Healthcare', 'Outcomes'],
  },
  {
    id: 'chunk-p-010',
    title: 'Board member of several major organizations',
    meaning: 'Glen serves on multiple corporate and nonprofit boards, including the Broad Institute of MIT and Harvard, where he contributes expertise on digital health and healthcare innovation.',
    quote: 'Board service allows me to learn from brilliant people tackling different challenges. Whether it\'s genomics at the Broad Institute or education reform, these experiences inform my thinking about healthcare transformation.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 24',
    sourceDomain: 'broadinstitute.org',
    sourceUrl: 'https://broadinstitute.org/board',
    status: 'pending',
    flaggedCount: 0,
    relationships: [],
    firstSeenAt: 'Oct 24, 2024, 10:30 AM',
    tags: ['Career', 'Leadership', 'Board'],
  },
  {
    id: 'chunk-p-011',
    title: 'Pioneer in applied health signals technology',
    meaning: 'Glen pioneered the concept of "applied health signals"—using real-time data from devices and sensors to provide personalized, timely interventions that help people manage their health more effectively.',
    quote: 'Health signals are everywhere—from your glucose monitor to your fitness tracker to your pharmacy refills. The magic happens when you apply AI to those signals to deliver the right intervention at exactly the right moment.',
    sourceType: 'upload',
    sourceName: 'glen-ted-talk-2018.txt',
    status: 'pending',
    flaggedCount: 4,
    relationships: [
      {
        type: 'flagged_from',
        actor: 'Aaron Thomas',
        at: 'Oct 22, 2024, 11:00 AM',
        reason: 'Great quote - consider featuring prominently',
      },
      {
        type: 'flagged_from',
        actor: 'Ashley',
        at: 'Oct 22, 2024, 2:15 PM',
        reason: 'Core to Glen\'s philosophy',
      },
      {
        type: 'flagged_from',
        actor: 'Glen',
        at: 'Oct 23, 2024, 9:00 AM',
        reason: 'This is central to my work - approve',
      },
      {
        type: 'flagged_from',
        actor: 'Aaron Thomas',
        at: 'Oct 23, 2024, 3:30 PM',
        reason: 'Add examples of specific signals',
      },
    ],
    firstSeenAt: 'Oct 22, 2024, 9:45 AM',
    lastSeenAt: 'Oct 23, 2024, 3:30 PM',
    tags: ['Technology', 'Innovation', 'AI', 'Healthcare'],
  },
  {
    id: 'chunk-p-012',
    title: 'Passionate about health equity and access',
    meaning: 'A core theme in Glen\'s work is addressing health disparities and ensuring that innovative healthcare solutions are accessible to all populations, not just the privileged few.',
    quote: 'Innovation means nothing if it only reaches people who can afford it. True healthcare transformation requires us to design solutions that work for everyone—regardless of income, location, or background.',
    sourceType: 'url',
    sourceName: 'Forbes Interview',
    sourceDomain: 'forbes.com',
    sourceUrl: 'https://forbes.com/glen-tullman-health-equity',
    status: 'pending',
    flaggedCount: 1,
    relationships: [
      {
        type: 'flagged_from',
        actor: 'Ashley',
        at: 'Oct 24, 2024, 8:15 AM',
        reason: 'Important value statement',
      },
    ],
    firstSeenAt: 'Oct 23, 2024, 6:00 PM',
    lastSeenAt: 'Oct 24, 2024, 8:15 AM',
    tags: ['Philosophy', 'Healthcare', 'Mission'],
  },

  // LIVE CHUNKS (20 total)
  {
    id: 'chunk-l-001',
    title: 'Founded Livongo with mission to empower people with chronic conditions',
    meaning: 'Livongo was founded on the principle that people with chronic conditions shouldn\'t just manage their disease—they should be empowered to live their best lives through technology and personalized support.',
    quote: 'When we started Livongo, we rejected the idea that having diabetes or hypertension meant settling for a diminished life. Technology should empower people to thrive, not just survive.',
    sourceType: 'upload',
    sourceName: 'glen-bio.pdf',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 15, 2024, 9:00 AM',
      },
    ],
    firstSeenAt: 'Oct 12, 2024, 10:00 AM',
    lastSeenAt: 'Oct 15, 2024, 9:00 AM',
    tags: ['Philosophy', 'Company', 'Livongo', 'Healthcare'],
  },
  {
    id: 'chunk-l-002',
    title: 'Believes technology should be human-centered',
    meaning: 'Glen advocates that healthcare technology must be designed around human needs and behaviors, not just technical capabilities. The best technology is invisible and intuitive.',
    quote: 'Too much health tech is built by engineers for engineers. We need to design for real people—busy parents, working professionals, elderly patients. If it\'s not simple and intuitive, it won\'t get used.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 10',
    sourceDomain: 'techcrunch.com',
    sourceUrl: 'https://techcrunch.com/glen-tullman-human-centered-design',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Aaron Thomas',
        at: 'Oct 14, 2024, 2:30 PM',
      },
    ],
    firstSeenAt: 'Oct 10, 2024, 3:15 PM',
    lastSeenAt: 'Oct 14, 2024, 2:30 PM',
    tags: ['Philosophy', 'Technology'],
  },
  {
    id: 'chunk-l-003',
    title: 'Grew up in Chicago area',
    meaning: 'Glen Tullman was raised in the Chicago area and has maintained strong ties to the region throughout his career, including service on local boards and investment in Chicago-based startups.',
    quote: 'Chicago shaped who I am—it\'s a city that values hard work, innovation, and community. I\'m proud to continue building companies here and giving back to the region that gave me so much.',
    sourceType: 'manual',
    sourceName: 'Manual Entry',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 10, 2024, 11:00 AM',
      },
    ],
    firstSeenAt: 'Oct 8, 2024, 9:00 AM',
    lastSeenAt: 'Oct 10, 2024, 11:00 AM',
    tags: ['Career'],
  },
  {
    id: 'chunk-l-004',
    title: 'Graduate of Bucknell University',
    meaning: 'Glen earned his undergraduate degree from Bucknell University, where he developed foundational business and leadership skills that would serve him throughout his career.',
    quote: 'Bucknell gave me more than an education—it taught me how to think critically, work collaboratively, and lead with purpose. Those lessons have stayed with me through every venture.',
    sourceType: 'url',
    sourceName: 'LinkedIn Profile',
    sourceDomain: 'linkedin.com',
    sourceUrl: 'https://linkedin.com/in/glentullman',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Ashley',
        at: 'Oct 12, 2024, 4:00 PM',
      },
    ],
    firstSeenAt: 'Oct 11, 2024, 2:00 PM',
    lastSeenAt: 'Oct 12, 2024, 4:00 PM',
    tags: ['Career'],
  },
  {
    id: 'chunk-l-005',
    title: 'Father of three children',
    meaning: 'Glen is a father of three and often speaks about how his family experiences with healthcare have influenced his professional mission to improve the system.',
    quote: 'Being a parent gives you a different perspective on healthcare. When your child is sick or needs care, you see all the friction, confusion, and frustration in the system. That personal experience drives my work every day.',
    sourceType: 'upload',
    sourceName: 'podcast-transcript-2022.txt',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 13, 2024, 10:30 AM',
      },
    ],
    firstSeenAt: 'Oct 12, 2024, 8:00 AM',
    lastSeenAt: 'Oct 13, 2024, 10:30 AM',
    tags: ['Healthcare', 'Philosophy'],
  },
  {
    id: 'chunk-l-006',
    title: 'One child has Type 1 diabetes',
    meaning: 'Glen\'s personal experience as the father of a child with Type 1 diabetes deeply influenced his decision to found Livongo and his passion for chronic disease management.',
    quote: 'When my son was diagnosed with Type 1 diabetes, I saw firsthand how inadequate our tools and support systems were. That experience made it personal—I wanted to build the solution I wished existed for my family.',
    sourceType: 'upload',
    sourceName: 'glen-bio.pdf',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 10, 2024, 9:30 AM',
      },
    ],
    firstSeenAt: 'Oct 8, 2024, 11:00 AM',
    lastSeenAt: 'Oct 10, 2024, 9:30 AM',
    tags: ['Healthcare', 'Philosophy', 'Livongo'],
  },
  {
    id: 'chunk-l-007',
    title: 'Regular speaker at major healthcare conferences',
    meaning: 'Glen is a sought-after speaker at industry events including HIMSS, JPMorgan Healthcare Conference, and various innovation summits where he shares insights on digital health transformation.',
    quote: 'Speaking at conferences isn\'t about self-promotion—it\'s about sharing what we\'ve learned, challenging conventional thinking, and inspiring others to push the boundaries of what\'s possible in healthcare.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 5',
    sourceDomain: 'himss.org',
    sourceUrl: 'https://himss.org/speakers/glen-tullman',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Aaron Thomas',
        at: 'Oct 9, 2024, 3:00 PM',
      },
    ],
    firstSeenAt: 'Oct 5, 2024, 1:30 PM',
    lastSeenAt: 'Oct 9, 2024, 3:00 PM',
    tags: ['Career', 'Leadership'],
  },
  {
    id: 'chunk-l-008',
    title: 'Investor in numerous healthcare startups',
    meaning: 'Through 7wireVentures and personal investments, Glen actively supports early-stage healthcare companies that are working to solve critical problems in the industry.',
    quote: 'I invest in companies led by passionate founders who are tackling real problems with innovative solutions. It\'s not about financial returns—it\'s about accelerating change in healthcare.',
    sourceType: 'url',
    sourceName: '7wire Ventures Website',
    sourceDomain: '7wireventures.com',
    sourceUrl: 'https://7wireventures.com/team/glen-tullman',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Ashley',
        at: 'Oct 11, 2024, 11:00 AM',
      },
    ],
    firstSeenAt: 'Oct 9, 2024, 4:00 PM',
    lastSeenAt: 'Oct 11, 2024, 11:00 AM',
    tags: ['Career', 'Company', 'Healthcare'],
  },
  {
    id: 'chunk-l-009',
    title: 'Believes in power of AI to transform healthcare',
    meaning: 'Glen sees artificial intelligence as a transformative force in healthcare, particularly in areas like personalized medicine, early detection, and clinical decision support.',
    quote: 'AI isn\'t replacing doctors—it\'s giving them superpowers. Imagine if every clinician had the collective knowledge of thousands of specialists available instantly. That\'s the promise of AI in healthcare.',
    sourceType: 'upload',
    sourceName: 'ai-healthcare-summit-2023.txt',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 14, 2024, 8:00 AM',
      },
    ],
    firstSeenAt: 'Oct 12, 2024, 2:00 PM',
    lastSeenAt: 'Oct 14, 2024, 8:00 AM',
    tags: ['Technology', 'AI', 'Healthcare', 'Philosophy'],
  },
  {
    id: 'chunk-l-010',
    title: 'Advocates for consumer empowerment in healthcare',
    meaning: 'A central tenet of Glen\'s philosophy is that patients should have more control, choice, and transparency in their healthcare decisions, similar to other consumer experiences.',
    quote: 'Healthcare is the only industry where consumers have no idea what something costs until after they buy it. We need to bring transparency, choice, and accountability to healthcare the way we have in every other part of our lives.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 8',
    sourceDomain: 'forbes.com',
    sourceUrl: 'https://forbes.com/glen-tullman-consumer-healthcare',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Aaron Thomas',
        at: 'Oct 12, 2024, 10:00 AM',
      },
    ],
    firstSeenAt: 'Oct 8, 2024, 3:00 PM',
    lastSeenAt: 'Oct 12, 2024, 10:00 AM',
    tags: ['Philosophy', 'Healthcare'],
  },
  {
    id: 'chunk-l-011',
    title: 'Emphasizes importance of data privacy and security',
    meaning: 'Glen is vocal about the need for robust data privacy protections in healthcare technology, believing that consumer trust is foundational to digital health adoption.',
    quote: 'People won\'t share their health data—and they shouldn\'t—unless they trust that it will be protected and used only for their benefit. Privacy and security aren\'t optional; they\'re the foundation of everything we do.',
    sourceType: 'upload',
    sourceName: 'cybersecurity-panel-2022.txt',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 10, 2024, 2:00 PM',
      },
    ],
    firstSeenAt: 'Oct 9, 2024, 11:00 AM',
    lastSeenAt: 'Oct 10, 2024, 2:00 PM',
    tags: ['Technology', 'Healthcare', 'Philosophy'],
  },
  {
    id: 'chunk-l-012',
    title: 'Known for accessible, straightforward communication style',
    meaning: 'Glen is recognized for his ability to explain complex healthcare concepts in simple, relatable terms that resonate with diverse audiences from patients to investors.',
    quote: 'If you can\'t explain something simply, you don\'t understand it well enough. Healthcare is complicated, but our communication about it doesn\'t have to be.',
    sourceType: 'manual',
    sourceName: 'Manual Entry',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Ashley',
        at: 'Oct 13, 2024, 3:00 PM',
      },
    ],
    firstSeenAt: 'Oct 12, 2024, 9:00 AM',
    lastSeenAt: 'Oct 13, 2024, 3:00 PM',
    tags: ['Philosophy'],
  },
  {
    id: 'chunk-l-013',
    title: 'Focused on measuring outcomes that matter',
    meaning: 'Glen advocates for healthcare metrics that reflect what patients actually care about—quality of life, functional ability, and overall wellbeing—not just clinical markers.',
    quote: 'We measure what\'s easy to measure, not what matters. A patient doesn\'t care about their A1C number—they care about living without complications, seeing their grandchildren grow up, and enjoying life.',
    sourceType: 'url',
    sourceName: 'WSJ Article',
    sourceDomain: 'wsj.com',
    sourceUrl: 'https://wsj.com/healthcare-outcomes-measurement',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 11, 2024, 4:00 PM',
      },
    ],
    firstSeenAt: 'Oct 10, 2024, 10:00 AM',
    lastSeenAt: 'Oct 11, 2024, 4:00 PM',
    tags: ['Philosophy', 'Healthcare', 'Outcomes'],
  },
  {
    id: 'chunk-l-014',
    title: 'Built multiple companies from startup to scale',
    meaning: 'Glen has demonstrated repeatable success in building healthcare technology companies from early-stage ventures to large-scale enterprises serving millions of people.',
    quote: 'Scaling a company isn\'t just about growing revenue—it\'s about maintaining your culture, your mission, and your commitment to quality while serving exponentially more people.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 3',
    sourceDomain: 'techcrunch.com',
    sourceUrl: 'https://techcrunch.com/glen-tullman-scaling-companies',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Aaron Thomas',
        at: 'Oct 7, 2024, 1:00 PM',
      },
    ],
    firstSeenAt: 'Oct 3, 2024, 2:00 PM',
    lastSeenAt: 'Oct 7, 2024, 1:00 PM',
    tags: ['Career', 'Company', 'Leadership'],
  },
  {
    id: 'chunk-l-015',
    title: 'Mentor to many healthcare entrepreneurs',
    meaning: 'Glen actively mentors early-stage healthcare founders, sharing lessons learned and helping them navigate the complex intersection of healthcare, technology, and business.',
    quote: 'The next generation of healthcare leaders will solve problems we haven\'t even identified yet. My job is to share what I\'ve learned so they can move faster and avoid the mistakes I made.',
    sourceType: 'upload',
    sourceName: 'startup-grind-interview-2021.txt',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Ashley',
        at: 'Oct 9, 2024, 9:00 AM',
      },
    ],
    firstSeenAt: 'Oct 7, 2024, 3:00 PM',
    lastSeenAt: 'Oct 9, 2024, 9:00 AM',
    tags: ['Career', 'Leadership'],
  },
  {
    id: 'chunk-l-016',
    title: 'Believes healthcare should be a right, not a privilege',
    meaning: 'Glen advocates for universal access to quality healthcare and works to build solutions that reduce disparities and make care accessible regardless of socioeconomic status.',
    quote: 'In the wealthiest country in the world, no one should have to choose between paying for medicine and paying rent. Healthcare is a human right, and we have the resources and technology to make it accessible to everyone.',
    sourceType: 'url',
    sourceName: 'Forbes Interview',
    sourceDomain: 'forbes.com',
    sourceUrl: 'https://forbes.com/glen-tullman-healthcare-access',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 8, 2024, 11:00 AM',
      },
    ],
    firstSeenAt: 'Oct 6, 2024, 4:00 PM',
    lastSeenAt: 'Oct 8, 2024, 11:00 AM',
    tags: ['Philosophy', 'Healthcare', 'Mission'],
  },
  {
    id: 'chunk-l-017',
    title: 'Focuses on solving real problems, not chasing technology trends',
    meaning: 'Glen prioritizes building solutions that address genuine healthcare pain points rather than implementing technology for its own sake.',
    quote: 'The graveyard of healthcare startups is filled with companies that built cool technology nobody needed. Start with the problem, not the technology. If you solve a real problem, the technology is just the means to an end.',
    sourceType: 'upload',
    sourceName: 'vc-pitch-advice-2020.txt',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Aaron Thomas',
        at: 'Oct 10, 2024, 8:00 AM',
      },
    ],
    firstSeenAt: 'Oct 8, 2024, 2:00 PM',
    lastSeenAt: 'Oct 10, 2024, 8:00 AM',
    tags: ['Philosophy', 'Technology'],
  },
  {
    id: 'chunk-l-018',
    title: 'Strong believer in preventive care and early intervention',
    meaning: 'Glen advocates for shifting healthcare resources toward prevention and early intervention rather than expensive late-stage treatment.',
    quote: 'We spend billions treating heart attacks and strokes that could have been prevented with early intervention. It\'s not just better for patients—it\'s smarter economics. Prevention saves lives and money.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 1',
    sourceDomain: 'healthaffairs.org',
    sourceUrl: 'https://healthaffairs.org/preventive-care-investment',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 5, 2024, 2:00 PM',
      },
    ],
    firstSeenAt: 'Oct 1, 2024, 11:00 AM',
    lastSeenAt: 'Oct 5, 2024, 2:00 PM',
    tags: ['Philosophy', 'Healthcare', 'Outcomes'],
  },
  {
    id: 'chunk-l-019',
    title: 'Understands importance of behavior change in health',
    meaning: 'Glen recognizes that sustainable health improvement requires behavior change, not just better information or tools, and designs solutions accordingly.',
    quote: 'Giving people data doesn\'t change behavior. What changes behavior is making the right choice the easy choice—removing friction, providing support at the right moment, and celebrating small wins.',
    sourceType: 'upload',
    sourceName: 'behavioral-health-conference-2019.txt',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Ashley',
        at: 'Oct 7, 2024, 10:00 AM',
      },
    ],
    firstSeenAt: 'Oct 5, 2024, 3:00 PM',
    lastSeenAt: 'Oct 7, 2024, 10:00 AM',
    tags: ['Philosophy', 'Healthcare'],
  },
  {
    id: 'chunk-l-020',
    title: 'Values building high-performing, mission-driven teams',
    meaning: 'Glen emphasizes the importance of company culture and hiring people who are motivated by mission, not just compensation, to build lasting organizations.',
    quote: 'The best teams aren\'t built with compensation packages—they\'re built with a compelling mission, mutual respect, and genuine belief that the work matters. When people feel purpose, they do extraordinary things.',
    sourceType: 'url',
    sourceName: 'LinkedIn Article',
    sourceDomain: 'linkedin.com',
    sourceUrl: 'https://linkedin.com/pulse/building-mission-driven-teams-glen-tullman',
    status: 'live',
    flaggedCount: 0,
    relationships: [
      {
        type: 'approved_by',
        actor: 'Glen',
        at: 'Oct 6, 2024, 9:00 AM',
      },
    ],
    firstSeenAt: 'Oct 4, 2024, 1:00 PM',
    lastSeenAt: 'Oct 6, 2024, 9:00 AM',
    tags: ['Philosophy', 'Leadership', 'Company'],
  },

  // DISMISSED CHUNKS (8 total)
  {
    id: 'chunk-d-001',
    title: 'Glen prefers casual dress code in the office',
    meaning: 'Unlike traditional healthcare executives, Glen favors a casual work environment where jeans and sneakers are the norm rather than suits and ties.',
    quote: 'I think people do their best work when they\'re comfortable. Formal dress codes are relics of a different era—what matters is the quality of your ideas, not what you\'re wearing.',
    sourceType: 'manual',
    sourceName: 'Manual Entry',
    status: 'dismissed',
    flaggedCount: 0,
    relationships: [
      {
        type: 'dismissed_by',
        actor: 'Glen',
        at: 'Oct 15, 2024, 3:00 PM',
        reason: 'Too trivial for AI twin',
      },
    ],
    firstSeenAt: 'Oct 14, 2024, 11:00 AM',
    lastSeenAt: 'Oct 15, 2024, 3:00 PM',
    tags: [],
  },
  {
    id: 'chunk-d-002',
    title: 'Favorite restaurant is RPM Italian in Chicago',
    meaning: 'Glen frequently dines at RPM Italian for business meetings and enjoys their modern take on Italian cuisine.',
    quote: 'Great food and great conversation—RPM Italian is the perfect setting for both. Plus, the location makes it easy for out-of-town guests.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 12',
    sourceDomain: 'eater.com',
    status: 'dismissed',
    flaggedCount: 0,
    relationships: [
      {
        type: 'dismissed_by',
        actor: 'Aaron Thomas',
        at: 'Oct 16, 2024, 9:00 AM',
        reason: 'Not relevant to professional expertise',
      },
    ],
    firstSeenAt: 'Oct 12, 2024, 2:00 PM',
    lastSeenAt: 'Oct 16, 2024, 9:00 AM',
    tags: [],
  },
  {
    id: 'chunk-d-003',
    title: 'Drives a Tesla Model S',
    meaning: 'Glen drives a Tesla Model S and is an advocate for electric vehicles as part of broader environmental sustainability.',
    quote: 'Tesla showed that you don\'t have to compromise performance for sustainability. That\'s the kind of thinking we need in healthcare—better outcomes and lower costs aren\'t mutually exclusive.',
    sourceType: 'upload',
    sourceName: 'linkedin-post-archive.txt',
    status: 'dismissed',
    flaggedCount: 0,
    relationships: [
      {
        type: 'dismissed_by',
        actor: 'Ashley',
        at: 'Oct 14, 2024, 2:00 PM',
        reason: 'Personal detail, not professional insight',
      },
    ],
    firstSeenAt: 'Oct 13, 2024, 10:00 AM',
    lastSeenAt: 'Oct 14, 2024, 2:00 PM',
    tags: [],
  },
  {
    id: 'chunk-d-004',
    title: 'Enjoys cycling on weekends',
    meaning: 'Glen is an avid cyclist who uses weekend bike rides as both exercise and time for reflection and creative thinking.',
    quote: 'Some of my best ideas come when I\'m on a bike. There\'s something about the rhythm of cycling that helps me think clearly and see problems from new angles.',
    sourceType: 'manual',
    sourceName: 'Manual Entry',
    status: 'dismissed',
    flaggedCount: 0,
    relationships: [
      {
        type: 'dismissed_by',
        actor: 'Glen',
        at: 'Oct 13, 2024, 4:00 PM',
        reason: 'Too personal for AI twin',
      },
    ],
    firstSeenAt: 'Oct 12, 2024, 3:00 PM',
    lastSeenAt: 'Oct 13, 2024, 4:00 PM',
    tags: [],
  },
  {
    id: 'chunk-d-005',
    title: 'Has a dog named Winston',
    meaning: 'Glen owns a golden retriever named Winston who occasionally appears in social media posts.',
    quote: 'Winston reminds me to take breaks and not take myself too seriously. Dogs have that gift.',
    sourceType: 'url',
    sourceName: 'Instagram Post',
    sourceDomain: 'instagram.com',
    status: 'dismissed',
    flaggedCount: 0,
    relationships: [
      {
        type: 'dismissed_by',
        actor: 'Aaron Thomas',
        at: 'Oct 15, 2024, 11:00 AM',
        reason: 'Not relevant to professional context',
      },
    ],
    firstSeenAt: 'Oct 14, 2024, 4:00 PM',
    lastSeenAt: 'Oct 15, 2024, 11:00 AM',
    tags: [],
  },
  {
    id: 'chunk-d-006',
    title: 'Watches Chicago Cubs games regularly',
    meaning: 'As a lifelong Chicago resident, Glen is a dedicated Cubs fan and occasionally attends games at Wrigley Field.',
    quote: 'Being a Cubs fan teaches you patience and resilience—qualities that also happen to be essential for building healthcare companies.',
    sourceType: 'perplexity',
    sourceName: 'Perplexity Scan Oct 10',
    sourceDomain: 'twitter.com',
    status: 'dismissed',
    flaggedCount: 0,
    relationships: [
      {
        type: 'dismissed_by',
        actor: 'Ashley',
        at: 'Oct 16, 2024, 10:00 AM',
        reason: 'Personal hobby, not professional insight',
      },
    ],
    firstSeenAt: 'Oct 10, 2024, 5:00 PM',
    lastSeenAt: 'Oct 16, 2024, 10:00 AM',
    tags: [],
  },
  {
    id: 'chunk-d-007',
    title: 'Collects vintage watches',
    meaning: 'Glen has a collection of vintage timepieces and appreciates craftsmanship and attention to detail.',
    quote: 'A well-made watch is a reminder that quality and craftsmanship matter. The details make all the difference.',
    sourceType: 'manual',
    sourceName: 'Manual Entry',
    status: 'dismissed',
    flaggedCount: 0,
    relationships: [
      {
        type: 'dismissed_by',
        actor: 'Glen',
        at: 'Oct 17, 2024, 9:00 AM',
        reason: 'Personal hobby, doesn\'t belong in AI twin',
      },
    ],
    firstSeenAt: 'Oct 15, 2024, 2:00 PM',
    lastSeenAt: 'Oct 17, 2024, 9:00 AM',
    tags: [],
  },
  {
    id: 'chunk-d-008',
    title: 'Prefers morning meetings over afternoon ones',
    meaning: 'Glen schedules important meetings and creative work in the morning when he feels most energized and focused.',
    quote: 'I\'m a morning person. My best thinking happens between 6 AM and noon—that\'s when I tackle the hardest problems.',
    sourceType: 'upload',
    sourceName: 'productivity-tips-article.txt',
    status: 'dismissed',
    flaggedCount: 0,
    relationships: [
      {
        type: 'dismissed_by',
        actor: 'Aaron Thomas',
        at: 'Oct 17, 2024, 2:00 PM',
        reason: 'Too specific and personal for AI twin',
      },
    ],
    firstSeenAt: 'Oct 16, 2024, 3:00 PM',
    lastSeenAt: 'Oct 17, 2024, 2:00 PM',
    tags: [],
  },
];

export const MOCK_UPLOADED_CONTENT: UploadedContent[] = [
  {
    id: 'upload-001',
    name: 'glen-bio.pdf',
    type: 'pdf',
    uploadedAt: 'Oct 8, 2024, 9:00 AM',
    uploadedBy: 'Aaron Thomas',
    chunksGenerated: 6,
    chunkIds: ['chunk-p-002', 'chunk-l-001', 'chunk-l-006', 'chunk-p-005', 'chunk-l-005', 'chunk-p-007'],
  },
  {
    id: 'upload-002',
    name: 'q3-earnings-transcript.txt',
    type: 'text',
    uploadedAt: 'Oct 10, 2024, 2:00 PM',
    uploadedBy: 'Ashley',
    chunksGenerated: 0,
    chunkIds: [],
  },
  {
    id: 'upload-003',
    name: 'glen-ted-talk-2018.txt',
    type: 'text',
    uploadedAt: 'Oct 15, 2024, 11:00 AM',
    uploadedBy: 'Aaron Thomas',
    chunksGenerated: 3,
    chunkIds: ['chunk-p-011', 'chunk-l-009', 'chunk-l-012'],
  },
  {
    id: 'upload-004',
    name: 'healthcare-conference-2023.txt',
    type: 'text',
    uploadedAt: 'Oct 19, 2024, 2:40 PM',
    uploadedBy: 'Ashley',
    chunksGenerated: 2,
    chunkIds: ['chunk-p-009', 'chunk-l-013'],
  },
  {
    id: 'upload-005',
    name: 'transcarent-press-kit.pdf',
    type: 'pdf',
    uploadedAt: 'Oct 19, 2024, 8:30 AM',
    uploadedBy: 'Aaron Thomas',
    chunksGenerated: 1,
    chunkIds: ['chunk-p-005'],
  },
  {
    id: 'upload-006',
    name: 'podcast-transcript-2022.txt',
    type: 'text',
    uploadedAt: 'Oct 12, 2024, 8:00 AM',
    uploadedBy: 'Ashley',
    chunksGenerated: 1,
    chunkIds: ['chunk-l-005'],
  },
  {
    id: 'upload-007',
    name: 'ai-healthcare-summit-2023.txt',
    type: 'text',
    uploadedAt: 'Oct 12, 2024, 2:00 PM',
    uploadedBy: 'Aaron Thomas',
    chunksGenerated: 1,
    chunkIds: ['chunk-l-009'],
  },
  {
    id: 'upload-008',
    name: 'startup-grind-interview-2021.txt',
    type: 'text',
    uploadedAt: 'Oct 7, 2024, 3:00 PM',
    uploadedBy: 'Ashley',
    chunksGenerated: 1,
    chunkIds: ['chunk-l-015'],
  },
];

export const MOCK_GUARDRAIL_TOPICS: GuardrailTopic[] = [
  {
    id: 'topic-001',
    value: 'Politics and Political Candidates',
    note: 'Avoid discussing political parties, candidates, or partisan issues',
    createdAt: 'Oct 5, 2024, 9:00 AM',
    createdBy: 'Aaron Thomas',
  },
  {
    id: 'topic-002',
    value: 'Religion and Religious Beliefs',
    note: 'Do not discuss personal religious views or make religious recommendations',
    createdAt: 'Oct 5, 2024, 9:05 AM',
    createdBy: 'Aaron Thomas',
  },
  {
    id: 'topic-003',
    value: 'Personal Health Details',
    note: 'Avoid discussing Glen\'s specific personal health information beyond what\'s public (son\'s T1D)',
    createdAt: 'Oct 6, 2024, 10:30 AM',
    createdBy: 'Glen',
  },
  {
    id: 'topic-004',
    value: 'Confidential Business Information',
    note: 'Never discuss unreleased products, financials, or strategic plans',
    createdAt: 'Oct 8, 2024, 2:00 PM',
    createdBy: 'Ashley',
  },
  {
    id: 'topic-005',
    value: 'Specific Medical Advice',
    note: 'Do not provide personalized medical recommendations or diagnoses',
    createdAt: 'Oct 10, 2024, 11:00 AM',
    createdBy: 'Aaron Thomas',
  },
  {
    id: 'topic-006',
    value: 'Controversial Social Issues',
    note: 'Steer clear of polarizing social topics unrelated to healthcare',
    createdAt: 'Oct 12, 2024, 3:00 PM',
    createdBy: 'Ashley',
  },
];

export const MOCK_GUARDRAIL_PHRASES: GuardrailPhrase[] = [
  {
    id: 'phrase-001',
    value: 'That\'s a wonderful question',
    rewriteHint: 'Just answer directly without the preamble',
    createdAt: 'Oct 5, 2024, 9:30 AM',
    createdBy: 'Aaron Thomas',
  },
  {
    id: 'phrase-002',
    value: 'Honestly',
    rewriteHint: 'Remove filler words - be direct and confident',
    createdAt: 'Oct 5, 2024, 9:35 AM',
    createdBy: 'Aaron Thomas',
  },
  {
    id: 'phrase-003',
    value: 'I\'m not sure about that, but',
    rewriteHint: 'Avoid uncertain language - either know or acknowledge limitation clearly',
    createdAt: 'Oct 7, 2024, 11:00 AM',
    createdBy: 'Glen',
  },
  {
    id: 'phrase-004',
    value: 'As an AI',
    rewriteHint: 'Never break the fourth wall - respond as Glen would',
    createdAt: 'Oct 9, 2024, 2:00 PM',
    createdBy: 'Ashley',
  },
  {
    id: 'phrase-005',
    value: 'Let me tell you',
    rewriteHint: 'Remove unnecessary lead-in phrases',
    createdAt: 'Oct 11, 2024, 4:00 PM',
    createdBy: 'Aaron Thomas',
  },
];
