"""Add feedback field to Vote_v2

Revision ID: 0165c8109465
Revises: cde308fedecc
Create Date: 2025-12-14 22:43:08.160022

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0165c8109465"
down_revision: Union[str, None] = "cde308fedecc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Vote_v2", sa.Column("feedback", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Vote_v2", "feedback")
    # ### end Alembic commands ###
