"""Add PasswordResetToken table

Revision ID: 03f024bc0478
Revises: 11697a81b452
Create Date: 2025-12-13 21:05:27.022227

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03f024bc0478"
down_revision: Union[str, None] = "11697a81b452"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PasswordResetToken",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_PasswordResetToken_expires_at"), "PasswordResetToken", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_PasswordResetToken_token"), "PasswordResetToken", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_PasswordResetToken_user_id"), "PasswordResetToken", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_PasswordResetToken_user_id"), table_name="PasswordResetToken")
    op.drop_index(op.f("ix_PasswordResetToken_token"), table_name="PasswordResetToken")
    op.drop_index(op.f("ix_PasswordResetToken_expires_at"), table_name="PasswordResetToken")
    op.drop_table("PasswordResetToken")
    # ### end Alembic commands ###
