"""Add password_changed_at to User table for session invalidation

Revision ID: 0b38154b6e6c
Revises: b0e0262481e1
Create Date: 2025-12-14 20:19:51.282403

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b38154b6e6c"
down_revision: Union[str, None] = "b0e0262481e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PasswordResetAttempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_PasswordResetAttempt_attempted_at"),
        "PasswordResetAttempt",
        ["attempted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_PasswordResetAttempt_user_id"), "PasswordResetAttempt", ["user_id"], unique=False
    )
    op.add_column("User", sa.Column("password_changed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "password_changed_at")
    op.drop_index(op.f("ix_PasswordResetAttempt_user_id"), table_name="PasswordResetAttempt")
    op.drop_index(op.f("ix_PasswordResetAttempt_attempted_at"), table_name="PasswordResetAttempt")
    op.drop_table("PasswordResetAttempt")
    # ### end Alembic commands ###
