"""Make isUpvoted nullable to allow feedback-only

Revision ID: 4af0ed37be0c
Revises: 0165c8109465
Create Date: 2025-12-14 22:56:50.340254

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4af0ed37be0c"
down_revision: Union[str, None] = "0165c8109465"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Vote_v2", "isUpvoted", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Vote_v2", "isUpvoted", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
