"""Initial schema

Revision ID: 992ca1e91852
Revises:
Create Date: 2025-12-03 13:12:59.736255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '992ca1e91852'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Chat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('lastContext', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id', 'createdAt')
    )
    op.create_table('Message_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatId', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('parts', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['Chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Stream',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['Chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Suggestion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documentId', sa.UUID(), nullable=False),
    sa.Column('documentCreatedAt', sa.DateTime(), nullable=False),
    sa.Column('originalText', sa.Text(), nullable=False),
    sa.Column('suggestedText', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isResolved', sa.Boolean(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documentId', 'documentCreatedAt'], ['Document.id', 'Document.createdAt'], name='fk_suggestion_document'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vote_v2',
    sa.Column('chatId', sa.UUID(), nullable=False),
    sa.Column('messageId', sa.UUID(), nullable=False),
    sa.Column('isUpvoted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['Chat.id'], ),
    sa.ForeignKeyConstraint(['messageId'], ['Message_v2.id'], ),
    sa.PrimaryKeyConstraint('chatId', 'messageId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vote_v2')
    op.drop_table('Suggestion')
    op.drop_table('Stream')
    op.drop_table('Message_v2')
    op.drop_table('Document')
    op.drop_table('Chat')
    op.drop_table('User')
    # ### end Alembic commands ###

