"""Add LoginAttempt table for account lockout

Revision ID: ab52bc8df839
Revises: 03f024bc0478
Create Date: 2025-12-13 21:18:05.040302

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab52bc8df839"
down_revision: Union[str, None] = "03f024bc0478"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "LoginAttempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_LoginAttempt_attempted_at"), "LoginAttempt", ["attempted_at"], unique=False
    )
    op.create_index(op.f("ix_LoginAttempt_user_id"), "LoginAttempt", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_LoginAttempt_user_id"), table_name="LoginAttempt")
    op.drop_index(op.f("ix_LoginAttempt_attempted_at"), table_name="LoginAttempt")
    op.drop_table("LoginAttempt")
    # ### end Alembic commands ###
