"""Add type field to User table

Revision ID: b0e0262481e1
Revises: ab52bc8df839
Create Date: 2025-12-14 02:15:39.028369

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0e0262481e1"
down_revision: Union[str, None] = "ab52bc8df839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable initially
    op.add_column("User", sa.Column("type", sa.String(length=10), nullable=True))

    # Step 2: Backfill existing users based on email pattern
    # Guest users have emails like: guest-{uuid}@anonymous.local
    op.execute("""
        UPDATE "User"
        SET type = 'guest'
        WHERE email LIKE 'guest-%@anonymous.local'
    """)

    # Set all remaining users to 'regular'
    op.execute("""
        UPDATE "User"
        SET type = 'regular'
        WHERE type IS NULL
    """)

    # Step 3: Make column NOT NULL with default
    op.alter_column("User", "type", nullable=False, server_default="regular")

    # Step 4: Add check constraint to ensure type is either 'guest' or 'regular'
    op.create_check_constraint("ck_user_type_valid", "User", "type IN ('guest', 'regular')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraint first
    op.drop_constraint("ck_user_type_valid", "User", type_="check")
    # Then drop the column
    op.drop_column("User", "type")
    # ### end Alembic commands ###
