"""Add RevokedToken table for JWT token revocation

Revision ID: cde308fedecc
Revises: 0b38154b6e6c
Create Date: 2025-12-14 21:54:52.779908

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cde308fedecc"
down_revision: Union[str, None] = "0b38154b6e6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "RevokedToken",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("jti", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_RevokedToken_expires_at"), "RevokedToken", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_RevokedToken_jti"), "RevokedToken", ["jti"], unique=True)
    op.create_index(
        op.f("ix_RevokedToken_revoked_at"), "RevokedToken", ["revoked_at"], unique=False
    )
    op.create_index(op.f("ix_RevokedToken_user_id"), "RevokedToken", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_RevokedToken_user_id"), table_name="RevokedToken")
    op.drop_index(op.f("ix_RevokedToken_revoked_at"), table_name="RevokedToken")
    op.drop_index(op.f("ix_RevokedToken_jti"), table_name="RevokedToken")
    op.drop_index(op.f("ix_RevokedToken_expires_at"), table_name="RevokedToken")
    op.drop_table("RevokedToken")
    # ### end Alembic commands ###
